/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BetStats {
  'totalLosses' : bigint,
  'totalBets' : bigint,
  'profitLoss' : number,
  'totalWins' : bigint,
  'totalAmount' : number,
}
export interface Bill {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'isPaid' : boolean,
  'remainingBalance' : number,
  'totalAmount' : number,
}
export interface BillSummary {
  'numUnpaid' : bigint,
  'totalOwed' : number,
  'totalPaid' : number,
  'numBills' : bigint,
  'totalRemaining' : number,
  'numPaid' : bigint,
}
export interface FullNNSData { 'maturity' : NNSMaturity, 'nnsState' : NNSState }
export interface Habit {
  'id' : bigint,
  'streak' : bigint,
  'goal' : bigint,
  'name' : string,
  'lastUpdated' : Time,
  'progress' : bigint,
}
export interface HorseBet {
  'id' : bigint,
  'odds' : number,
  'horseName' : string,
  'timestamp' : Time,
  'isWin' : boolean,
  'amount' : number,
}
export interface NNSMaturity {
  'earnedPerDay' : number,
  'lastUpdated' : Time,
  'earned' : number,
}
export interface NNSState { 'lastUpdated' : Time, 'stakedICP' : number }
export interface Payment {
  'id' : bigint,
  'timestamp' : Time,
  'amount' : number,
  'billId' : bigint,
}
export interface Plan {
  'id' : bigint,
  'title' : string,
  'links' : Array<string>,
  'notes' : string,
  'timestamp' : Time,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'priority' : bigint,
  'isComplete' : boolean,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBill' : ActorMethod<[Bill], undefined>,
  'addHabit' : ActorMethod<[Habit], undefined>,
  'addHorseBet' : ActorMethod<[HorseBet], undefined>,
  'addPayment' : ActorMethod<[Payment], undefined>,
  'addPlan' : ActorMethod<[Plan], undefined>,
  'addTask' : ActorMethod<[Task], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'deletePlan' : ActorMethod<[bigint], undefined>,
  'editBill' : ActorMethod<[bigint, Bill], undefined>,
  'fetchNNSLiveData' : ActorMethod<[string], string>,
  'getBetStats' : ActorMethod<[], BetStats>,
  'getBillPayments' : ActorMethod<[bigint], Array<Payment>>,
  'getBillSummary' : ActorMethod<[], BillSummary>,
  'getBills' : ActorMethod<[], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFullNNSData' : ActorMethod<[], FullNNSData>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getHorseBets' : ActorMethod<[], Array<HorseBet>>,
  'getNNSMaturity' : ActorMethod<[], NNSMaturity>,
  'getNNSState' : ActorMethod<[], NNSState>,
  'getPlans' : ActorMethod<[], Array<Plan>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateHabitProgress' : ActorMethod<[bigint, bigint], undefined>,
  'updateNNSMaturity' : ActorMethod<[NNSMaturity], undefined>,
  'updateNNSState' : ActorMethod<[NNSState], undefined>,
  'updatePlan' : ActorMethod<[bigint, Plan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];