/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isPaid' : IDL.Bool,
  'remainingBalance' : IDL.Float64,
  'totalAmount' : IDL.Float64,
});
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'streak' : IDL.Nat,
  'goal' : IDL.Nat,
  'name' : IDL.Text,
  'lastUpdated' : Time,
  'progress' : IDL.Nat,
});
export const HorseBet = IDL.Record({
  'id' : IDL.Nat,
  'odds' : IDL.Float64,
  'horseName' : IDL.Text,
  'timestamp' : Time,
  'isWin' : IDL.Bool,
  'amount' : IDL.Float64,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'billId' : IDL.Nat,
});
export const Plan = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'links' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'priority' : IDL.Nat,
  'isComplete' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BetStats = IDL.Record({
  'totalLosses' : IDL.Nat,
  'totalBets' : IDL.Nat,
  'profitLoss' : IDL.Float64,
  'totalWins' : IDL.Nat,
  'totalAmount' : IDL.Float64,
});
export const BillSummary = IDL.Record({
  'numUnpaid' : IDL.Nat,
  'totalOwed' : IDL.Float64,
  'totalPaid' : IDL.Float64,
  'numBills' : IDL.Nat,
  'totalRemaining' : IDL.Float64,
  'numPaid' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const NNSMaturity = IDL.Record({
  'earnedPerDay' : IDL.Float64,
  'lastUpdated' : Time,
  'earned' : IDL.Float64,
});
export const NNSState = IDL.Record({
  'lastUpdated' : Time,
  'stakedICP' : IDL.Float64,
});
export const FullNNSData = IDL.Record({
  'maturity' : NNSMaturity,
  'nnsState' : NNSState,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBill' : IDL.Func([Bill], [], []),
  'addHabit' : IDL.Func([Habit], [], []),
  'addHorseBet' : IDL.Func([HorseBet], [], []),
  'addPayment' : IDL.Func([Payment], [], []),
  'addPlan' : IDL.Func([Plan], [], []),
  'addTask' : IDL.Func([Task], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deletePlan' : IDL.Func([IDL.Nat], [], []),
  'editBill' : IDL.Func([IDL.Nat, Bill], [], []),
  'fetchNNSLiveData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getBetStats' : IDL.Func([], [BetStats], ['query']),
  'getBillPayments' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getBillSummary' : IDL.Func([], [BillSummary], ['query']),
  'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFullNNSData' : IDL.Func([], [FullNNSData], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getHorseBets' : IDL.Func([], [IDL.Vec(HorseBet)], ['query']),
  'getNNSMaturity' : IDL.Func([], [NNSMaturity], ['query']),
  'getNNSState' : IDL.Func([], [NNSState], ['query']),
  'getPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateHabitProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateNNSMaturity' : IDL.Func([NNSMaturity], [], []),
  'updateNNSState' : IDL.Func([NNSState], [], []),
  'updatePlan' : IDL.Func([IDL.Nat, Plan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isPaid' : IDL.Bool,
    'remainingBalance' : IDL.Float64,
    'totalAmount' : IDL.Float64,
  });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'streak' : IDL.Nat,
    'goal' : IDL.Nat,
    'name' : IDL.Text,
    'lastUpdated' : Time,
    'progress' : IDL.Nat,
  });
  const HorseBet = IDL.Record({
    'id' : IDL.Nat,
    'odds' : IDL.Float64,
    'horseName' : IDL.Text,
    'timestamp' : Time,
    'isWin' : IDL.Bool,
    'amount' : IDL.Float64,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'billId' : IDL.Nat,
  });
  const Plan = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'links' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'priority' : IDL.Nat,
    'isComplete' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BetStats = IDL.Record({
    'totalLosses' : IDL.Nat,
    'totalBets' : IDL.Nat,
    'profitLoss' : IDL.Float64,
    'totalWins' : IDL.Nat,
    'totalAmount' : IDL.Float64,
  });
  const BillSummary = IDL.Record({
    'numUnpaid' : IDL.Nat,
    'totalOwed' : IDL.Float64,
    'totalPaid' : IDL.Float64,
    'numBills' : IDL.Nat,
    'totalRemaining' : IDL.Float64,
    'numPaid' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const NNSMaturity = IDL.Record({
    'earnedPerDay' : IDL.Float64,
    'lastUpdated' : Time,
    'earned' : IDL.Float64,
  });
  const NNSState = IDL.Record({
    'lastUpdated' : Time,
    'stakedICP' : IDL.Float64,
  });
  const FullNNSData = IDL.Record({
    'maturity' : NNSMaturity,
    'nnsState' : NNSState,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBill' : IDL.Func([Bill], [], []),
    'addHabit' : IDL.Func([Habit], [], []),
    'addHorseBet' : IDL.Func([HorseBet], [], []),
    'addPayment' : IDL.Func([Payment], [], []),
    'addPlan' : IDL.Func([Plan], [], []),
    'addTask' : IDL.Func([Task], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deletePlan' : IDL.Func([IDL.Nat], [], []),
    'editBill' : IDL.Func([IDL.Nat, Bill], [], []),
    'fetchNNSLiveData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getBetStats' : IDL.Func([], [BetStats], ['query']),
    'getBillPayments' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getBillSummary' : IDL.Func([], [BillSummary], ['query']),
    'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFullNNSData' : IDL.Func([], [FullNNSData], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getHorseBets' : IDL.Func([], [IDL.Vec(HorseBet)], ['query']),
    'getNNSMaturity' : IDL.Func([], [NNSMaturity], ['query']),
    'getNNSState' : IDL.Func([], [NNSState], ['query']),
    'getPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateHabitProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateNNSMaturity' : IDL.Func([NNSMaturity], [], []),
    'updateNNSState' : IDL.Func([NNSState], [], []),
    'updatePlan' : IDL.Func([IDL.Nat, Plan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };